version: '3'
services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes
        volumes:
            - ./redis/data:/data
        restart: always
    backend:
        build: ./backend/.
        volumes:
            - "./backend:/backend"
            - "/backend/node_modules"
        ports:
            - "4201:6969"
    frontend:
        build: ./frontend/.
        stdin_open: true
        tty: true
        volumes:
            - "./frontend:/frontend"
            - "/frontend/node_modules"
        ports:
            - "4202:3000"